# Generated by Django 4.2 on 2023-05-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Folder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user',
            new_name='author',
        ),
    ]
