# Generated by Django 4.1.7 on 2023-05-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Folder', '0003_alter_workout_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='author',
            new_name='user',
        ),
    ]
